config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, path: 'auth', path_names: { sign_in: 'login',
                                                 sign_out: 'logout',
                                                 password: 'secret',
                                                 confirmation: 'verification',
                                                 unlock: 'unblock',
                                                 registration: 'register',
                                                 sign_up: 'cmon_let_me_in' }
  get '/users/:id', to: 'users#show', as: 'user'
  resources :events
  resources :users, only: :show do
    member do
      get :upcoming_events, :created_events, :past_attended_events
    end
  end
  resources :attendances, only: %i[create destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  include EventState
  include Filterable

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', counter_cache: :created_events_count
  belongs_to :category, class_name: 'Category', foreign_key: 'category_id'

  has_many :attendances, class_name: 'Attendance',
                         foreign_key: 'attending_event_id',
                         dependent: :destroy
  has_many :attendees, through: :attendances, source: :attendee

  scope :by_category, ->(category_id) { where category_id: category_id }
  scope :by_title, ->(title) { where("lower(title) LIKE ? OR lower(description) LIKE ?", "%#{title.downcase}%", "%#{title.downcase}%") }
  scope :start_date, ->(start_date) { where('date_and_time >= ?', start_date) }
  scope :end_date, ->(end_date) { where('date_and_time <= ?', end_date) }
  scope :by_date, -> { order(date_and_time: :desc) }
  scope :by_attendees_count, -> { order(attendees_count: :desc) }

  before_validation :normalize_title
  before_validation :create_slug

  validates_presence_of :user_id, :title, :venue, :address, :date_and_time,
                        :category_id, :description, :picture

  validates_length_of :title, :venue, maximum: 80
  validates_length_of :description, maximum: 2000
  validate :date_in_future

  mount_uploader :picture, ImageUploader
  validate :picture_size

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def per_page
    self.per_page = 15
  end

  def create_slug
    self.slug = title.parameterize
  end

  def self.popular_categories
    Event.includes(:category).upcoming.max_by(7) { |event| event.attendees_count }.map(&:category).uniq
  end

  private

  def normalize_title
    self.title = title.downcase.mb_chars.titleize
  end

  def picture_size
    errors.add(:picture, 'should be less than 10 MB') if picture.size > 10.megabytes
  end

  def date_in_future
    errors.add :date_and_time, 'should be at least one day from now' if date_and_time <= Time.zone.now
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :concatenate_date, only: %i[create update]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @events = search(params).paginate(page: params[:page])

    map_hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow render_to_string(partial: '/events/infowindow', locals: { object: event })
    end
    gon.mapHash = map_hash
    @categories = Category.pluck(:name, :id)
  end

  def show
    @event = Event.find(params[:id])
    map_hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow event.venue
    end
    gon.mapHash = map_hash
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = 'New event created'
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.includes(:creator).find(params[:id])
    if @event.past?
      flash[:danger] = 'You cannot edit past event!'
      redirect_to @event
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.past?
      flash[:danger] = 'You cannot edit past event!'
      redirect_to @event
    elsif @event.update_attributes(event_params)
      flash[:success] = 'Event updated'
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    Cloudinary::Api.delete_resources(@event.picture.public_id)
    @event.destroy
    flash[:success] = 'Event deleted'
    redirect_to user_path(current_user)
  end

  def search(params)
    events = Event.includes(:creator, :category)
                  .filter(params.slice(:by_category, :by_title, :start_date, :end_date))
                  .upcoming
                  .by_date
    events = events.near(params[:location]) if params[:location].present?
    events
  end

  private

  def event_params
    params.require(:event).permit(:title, :venue, :date_and_time, :description,
                                  :picture, :user_id, :category_id, :address)
  end

  # Before actions

  def concatenate_date
    params[:event][:date_and_time] = (params[:date] + ' ' + params[:time_submit]).to_datetime
  end

  def correct_user
    @event = Event.find(params[:id])
    if current_user != @event.creator
      redirect_to(root_url)
      flash[:alert] = 'You are not allowed to enter this section!'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def postcard_events(events)
    (render partial: 'events/event_postcard',
            collection: events,
            as: :event) ||
              (content_tag :h3,
                           'No events found',
                           class: 'title
                                   title--center
                                   text--skinny')
  end

  def list_events(events)
    (render partial: 'events/event_list',
            collection: events,
            as: :event) ||
              (content_tag :h3,
                           'No events found',
                           class: 'title
                                   title--center
                                   text--skinny')
  end
end

app/views/events/_aside-filter.html.erb
<!-- Events aside -->

<aside class="aside">

  <!-- Map of filtered events -->

  <div class='aside__map'>
    <div id='event-map' class='aside__map'></div>
  </div>

  <div class='aside__content'>


    <h3 class='title title--l3 title__container'>
      Filter events
      <%= svg('circle-down.svg', class: 'icon--filter') %>
    </h3>

    <!-- Filter form -->

    <div id='filter-form'>
      <%= form_tag :events, method: 'get' do %>

        <!-- Event's description -->
        <%= text_field_tag :by_title, params[:by_title], { class: 'form__field aside__item',
                                            placeholder: 'Event\'s title, description' } %>

        <!-- Event's location -->
        <%= text_field_tag :location, params[:location], { class: 'form__field aside__item',
                                            placeholder: 'Event\'s location' } %>

        <!-- Event's category -->
        <div class='aside__item'>
          <%= svg('circle-down.svg', class: 'select-icon') %>
          <%= select_tag :by_category,
                          options_for_select(@categories,
                          params[:by_category]),
                          { include_blank: 'Select category',
                            class: 'form__field form__select' } %>
        </div>

        <!-- Event's date -->
        <div class='aside__item aside__fromto'>

          <%= text_field_tag :start_date,
                            (params[:start_date].to_datetime.strftime("%e %b, %Y") unless params[:start_date].blank?),
                            { id: 'datepicker',
                              class: 'form__field form__field--half',
                              placeholder: 'From date...' } %>
          <%= text_field_tag :end_date,
                            (params[:end_date].to_datetime.strftime("%e %b, %Y") unless params[:end_date].blank?),
                            { id: 'datepicker2',
                              class: 'form__field form__field--half',
                              placeholder: '...to date' } %>
        </div>

        <%= submit_tag 'Search', { class: 'btn btn--notice aside__item', id: 'search' } %>
      <% end %>

      <%= button_to "Clear Search", events_path,
                                    method: 'get',
                                    class: 'btn btn--danger aside__item',
                                    id: 'clear-search' %>
    </div>
  </div>
</aside>

app/views/events/_attend-form.html.erb
<% if current_user %>
  <div id='attend-form' class='attend-form'>
    <% if current_user.attending?(@event) %>
      <%= render 'unattend' %>
    <% else %>
      <%= render 'attend' %>
    <% end %>
  </div>
<% end %>

app/views/events/_attend.html.erb
<%= form_for(current_user.attendances.build, remote: true) do |f| %>
  <%= hidden_field_tag :attending_event_id, @event.id %>
  <%= f.submit 'Attend event', class: 'btn btn--success' %>
<% end %>

app/views/events/_e-stash.html.erb
<!-- Event header -->

<div class='event__header'>
  <%= link_to event do %>

    <%= image_tag event.picture_url(:thumb_card),
                  class: class_string('event__image',
                        'img--grayscale' => event.past?),
                  alt: event.title %>
  <% end %>
</div>

<!-- Event stash -->

<div class='event__stash'>

  <!-- Event info -->

  <%= link_to event do %>

    <div class='event__info'>
      <%= time_tag event.date_and_time, event.date_and_time.strftime("%a, %d %b %Y %l:%M %p"), class: 'title--up title--l6' %>
      <%= content_tag(:h5, event.title, class: 'title--l4 title--clap-2 title--cpt') %>
      <%= content_tag(:h6, (event.venue + ', ').concat(event.address), class: 'title--l6 title--clap-1') %>
    </div>

  <% end %>

  <!-- Event footer -->

  <footer class='event__footer'>
    <%= link_to "##{event.category.name}",
                events_path(by_category: event.category.id),
                class: 'title--l6 link' %>
    <%= content_tag(:h6, "Attendees: #{event.attendees_count}", class: 'title--l6') %>
  </footer>
</div>

app/views/events/_event_list.html.erb
<article class='e-list__cell'>

  <!-- Event edit button -->

  <% if event.creator == current_user && event.upcoming? %>
    <div class='event__edit'><%= link_to('edit', edit_event_path(event), class: 'link-decorate') %></div>
  <% end %>

  <!-- Event content -->

  <div class='e-list__content'>

    <%= render 'events/e-stash', event: event %>

  </div>
</article>

app/views/events/_event_postcard.html.erb
<article class='e-card__cell'>

  <!-- Event edit button -->

  <% if event.creator == current_user && event.upcoming? %>
    <div class='event__edit'><%= link_to('edit', edit_event_path(event), class: 'link-decorate') %></div>
  <% end %>

  <!-- Event content -->

  <div class='e-card__content'>

    <%= render 'events/e-stash', event: event %>

  </div>
</article>

app/views/events/_form.html.erb
<%= form_for @event, html: { class: 'form' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <!-- Event's title -->
  <div class='form__group'>
    <%= f.label :title, class: 'title--l4' %>
    <%= f.text_field :title, required: true, autofocus: true,
                    placeholder: 'Short, distinct title', class: 'form__field' %>
  </div>

  <!-- Event's venue -->
  <div class='form__group'>
    <%= f.label :venue, class: 'title--l4' %>
    <%= f.text_field :venue, required: true, placeholder: 'Where it\'s held',
                     class: 'form__field' %>
  </div>

  <!-- Event's address -->
  <div class='form__group'>
    <%= f.label :address, class: 'title--l4' %>
    <%= f.text_field :address, required: true, placeholder: 'Venue\'s full address',
                     class: 'form__field' %>
  </div>

  <!-- Event's date and time -->
  <div class='form__group'>
    <%= f.label 'Date and time', class: 'title--l4' %>

    <div class='datetime-picker_container'>
      <%= text_field_tag :date,
                         (@event.date_and_time.strftime("%e %b, %Y") unless @event.date_and_time.nil?),
                         { id: 'datepicker',
                           class: 'form__field datetime-picker',
                           placeholder: 'Set event\'s date' } %>
      <%= text_field_tag :time,
                         (@event.date_and_time.strftime("%l:%M %p") unless @event.date_and_time.nil?),
                         { id: 'timepicker',
                           class: 'form__field datetime-picker',
                           placeholder: 'Set event\'s time' } %>
    </div>
  </div>

  <%= hidden_field_tag :date_and_time %>

  <!-- Event's category -->
  <div class='form__group'>
    <%= f.label :category, class: 'title--l4' %>
    <div class='select'>
      <%= svg('circle-down.svg', class: 'select-icon') %>
      <%= f.select :category_id, Category.pluck(:name, :id),
                                 { include_blank: 'Please select a category' },
                                 { class: 'form__field', required: true } %>
    </div>
  </div>

  <!-- Event's description -->
  <div class='form__group'>
    <%= f.label :description, class: 'title--l4' %>
    <%= f.text_area :description, placeholder: 'Provide a detailed description of your event',
                                  class: ' form__field form__textarea' %>
    <p class='text--smaller'>You can use <em>stong, em, a, h3, h4, h5, h6, p, ol, ul, li and hr</em> HTML tags.</p>
  </div>

  <!-- Event's picture -->
  <div class='form__group'>

    <% if @event.picture? %>
      <%= image_tag @event.picture_url(:thumb_card), class: 'form__img-thumb' %>
    <% end %>

    <%= f.file_field :picture, class: 'inputfile inputfile-1' %>
    <label for="event_picture"><%= svg('fileinput.svg') %>
      <% unless @event.new_record? %>
        <span>Update event image</span>
      <% else %>
        <span>Add event image</span>
      <% end %>
    </label>

    <p class='text--smaller'>Please use only 1 image, at least 1440x720px (2:1), max 10MB</p>
  </div>

  <!-- Event's submit btn -->
  <%= f.submit 'Make it live', class: 'btn btn--success btn--large' %>
<% end %>

app/views/events/_infowindow.html.erb
<%= link_to object.title, event_path(object), class: 'map_infowindow link-decorate' %>

app/views/events/_unattend.html.erb
<%= form_for(current_user.attendances.find_by(attending_event_id: @event.id),
            html: { method: :delete },
            remote: true) do |f| %>
  <div class='dont-attend-container'>
    <%= f.submit 'Attending', class: 'btn btn--notice', id: 'dont-attend-btn' %>
  </div>

<% end %>

app/views/events/edit.html.erb
<% provide(:title, 'Edit the event') %>

<section class='form__container'>
  <h2 class='title title--l1'><%= yield :title %></h2>
  <hr class='h-rule'>

<%= render 'form' %>

</section>

<section>
  <h4 class='title title--l3'>Want to delete the event?</h4>

  <%= button_to "Delete event", event_path,
                data: { confirm: "Are you sure?" }, method: :delete,
                class: 'btn btn--danger' %>
</section>

app/views/events/index.html.erb
<%= provide(:title, 'Search events') %>

<div class="eu-grid">

  <h2 class='eu__header--center title title--l1'><%= yield :title %></h2>

  <%= render 'aside-filter' %>

  <section class='eu__events'>
    <%= list_events @events %>
    <%= will_paginate %>
  </section>

</div>

app/views/events/new.html.erb
<% provide(:title, 'Create new event') %>

<section class='form__container'>
  <h2 class='title title--l1'><%= yield :title %></h2>

  <hr class='h-rule h-rule-5--grid-3'>

  <%= render 'form' %>

</section>

app/views/events/show.html.erb
<%= provide(:title, @event.title) %>

<%= render 'modal/modal' %>

<div class="event-listing-grid">

  <!-- Blurry hero image -->
  <div class="hero">
      <%= image_tag @event.picture_url,
                    class: class_string('hero__img--blurry',
                                        'hero__img--blurry--grayscale' => @event.past?) %>
  </div>

  <div class='event__container'>

    <!-- Event's edit btn -->
    <% if @event.creator == current_user && @event.upcoming? %>
      <div class='event__edit--big event__edit'>
        <%= link_to('edit', edit_event_path(@event), class: 'link') %>
      </div>
    <% end %>

    <!-- Event image -->
    <figure class='event__header'>

        <%= image_tag @event.picture_url(:show),
                      class: class_string('event__image',
                                          'img--grayscale' => @event.past?),
                      alt: @event.title %>
    </figure>

    <!-- Event header info -->
    <div class='event__header-info'>

      <div class='event__date'>
        <%= time_tag @event.date_and_time, '' do %>
          <%= content_tag :p, @event.date_and_time.strftime("%b"), class: 'text--smallest text--up text--muted' %>
          <%= content_tag :p, @event.date_and_time.strftime("%d"), class: 'text--up title--l3 text--muted' %>
        <% end %>
      </div>

      <div class='event__header-body'>
        <%= content_tag :h2, @event.title, class: 'title--l3' %>

        <h2 class='text--up title--l4 text--muted text--skinny  mt1'>
          Attendees:
          <span id='attendees-count' class='title--l4 text--muted'>
            <%= @event.attendees_count %>
          </span>
          <% if current_user == @event.creator %>
            <a href='#' id='modal-btn'>
              (See list)
            </a>
          <% end %>
        </h2>

        <p class='text--smaller text--skinny'>by <%= link_to @event.creator.name,
            user_path(@event.creator), class: 'link text--skinny' %></p>
      </div>
    </div>

    <!--- Event attend btn -->
    <div class='event__attend'>

      <% if current_user && @event.upcoming? %>
        <%= render 'attend-form' %>

      <% elsif @event.past? %>
        <p class='text--center'>This event was held on <%= @event.date_and_time.strftime("%a, %d %b %Y") %></p>

      <% else %>
        <p class='text--center'>
          <%= link_to 'Sign up', new_user_registration_path, class: 'link' %>
          &nbsp;
          or
          &nbsp;
          <%= link_to 'log in', new_user_session_path, class: 'link' %>
          &nbsp;
          to attend this event
        </p>
      <% end %>

    </div>

    <!-- Event's description -->
    <section class='event__description'>
      <%= content_tag :h3, 'Descripton', class: 'title--l4 text--up mb1' %>
      <div class='event__text text--preline'><%= sanitize @event.description, tags: %w(strong em a h3 h4 h5 h6 p hr ul ol li), attributes: %w(href) %></div>
    </section>

    <!-- Event's date, time and location info -->
    <aside class="event__aside-info event__text">

      <div class='aside__group'>
        <%= content_tag :h3, 'Date and time', class: 'title--l4 text--up mb1' %>
        <%= time_tag @event.date_and_time, @event.date_and_time.strftime("%a, %d %b %Y %l:%M %p") %>
      </div>

      <div class='aside__group'>
        <%= content_tag :h3, 'Location', class: 'title--l4 text--up mb1' %>
        <address>
          <% @event.venue.split(', ').each do |address_slice| %>
            <%= content_tag :p, address_slice, class: 'event__text' %>
          <% end %>
          <% @event.address.split(', ').each do |address_slice| %>
            <%= content_tag :p, address_slice, class: 'event__text' %>
          <% end %>
        </address>
      </div>

    </aside>

    <!-- Event's map -->
    <div class='event__map'>
      <div id='event-map' class='map'></div>
    </div>

    <!-- Event's location details and directions link -->
    <div class='event__location'>
      <%= content_tag :h2, @event.title, class: 'title--l3 text--center' %>
      <span class='text--muted text--smaller text--skinny text--center'>at</span>
      <%= content_tag :h2, @event.venue, class: 'title--l3 text--center' %>
      <%= content_tag :p, @event.address, class: 'text--smaller text--center' %>
      <%= link_to 'Directions',
                  "https://www.google.com/maps?saddr=My+Location&daddr=#{@event.latitude},#{@event.longitude}",
                   class: 'link text--smaller mt1',
                  target: '_blank' %>
    </div>
  </div>
</div>