config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, path: 'auth', path_names: { sign_in: 'login',
                                                 sign_out: 'logout',
                                                 password: 'secret',
                                                 confirmation: 'verification',
                                                 unlock: 'unblock',
                                                 registration: 'register',
                                                 sign_up: 'cmon_let_me_in' }
  get '/users/:id', to: 'users#show', as: 'user'
  resources :events
  resources :users, only: :show do
    member do
      get :upcoming_events, :created_events, :past_attended_events
    end
  end
  resources :attendances, only: %i[create destroy]
end

app/views/layouts/_footer.html.erb
<footer class='main-footer'>
  <section class='main-footer__content'>
    <h4 class='title--l4 text--white text--center'>© Mario Zugaj. EventBrite clone.</h4>
    <h4 class='title--l4 text--white text--center'>Project for 
      <%= link_to 'TheOdinProject',
                  'https://www.theodinproject.com/courses/ruby-on-rails/lessons/advanced-associations?ref=lc-pb',
                  class: 'link footer__link' %></h4>
  </section>
</footer>

app/views/layouts/_header.html.erb
<header class='main-header'>
  <%= link_to 'BrightEvents', root_path, id: 'logo', class: 'logo' %>

  <nav class='main-header__nav'>
    <label for='show-menu' class='show-menu'><%= svg('menu.svg', class: 'icon icon--menu') %></label>
    <input type='checkbox' id='show-menu' role='button'>
    <ul class='nav__menu'>
      <li class='nav__item'>
        <%= link_to 'Search events', events_path, class: 'nav__link' %>
      </li>
      <% if !user_signed_in? %>
        <li class='nav__item'>
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav__link' %>
        </li>
        <li class='nav__item'>
          <%= link_to 'Log in', new_user_session_path, class: 'nav__link' %>
        </li>
      <% else %>
        <li class='nav__item'>
          <a class='nav__link' onclick='return false;' href=''><%= svg('user.svg', class: 'icon') %><%=current_user.name %></a>
          <ul class='hidden'>
            <li class='nav__item'>
              <%= link_to 'Manage events', user_path(current_user), class: 'nav__link' %>
            </li>
            <li class='nav__item'>
              <%= link_to 'Edit account', edit_user_registration_path, class: 'nav__link' %>
            </li>
            <li class='nav__item'>
              <%= link_to 'Logout', destroy_user_session_path, class: 'nav__link', method: 'delete' %>
            </li>
          </ul>
        </li>
      <% end %>
      <li class='nav__item'>
        <%= link_to 'Create event', new_event_path, class: 'nav__link nav__link--reverse' %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= Gon::Base.render_data %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="//maps.google.com/maps/api/js?key=<%= ENV["GMAPS_API_KEY"] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <main class="main-grid">
      <%= render 'layouts/header' %>
      <%= render 'shared/flash' %>
      <div class='content'>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </main>
  </body>
</html>